# Generated by Django 5.0.1 on 2024-02-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novoprojeto', '0003_rename_quantidade_projetos_listagem_qtd_projetos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listagem',
            old_name='qtd_projetos',
            new_name='quantidade_projetos',
        ),
        migrations.RenameField(
            model_name='validacao',
            old_name='resposta',
            new_name='respondido',
        ),
    ]
