# Generated by Django 5.0.1 on 2024-02-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novoprojeto', '0005_alter_listagem_descricao_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validacao',
            old_name='acertou',
            new_name='aprovado',
        ),
        migrations.RenameField(
            model_name='validacao',
            old_name='respondido',
            new_name='executado',
        ),
    ]
